export const myData = {
  name: "Paweł Marcinkowski",
  description:
    "🧑🏽💻 I'm passionate Frontend Developer in love with React. Currently looking for first job opportunities.",
  email: "marcinkowski.pwl@gmail.com",
  github: "https://github.com/MarcinkPawel",
  link: "addLater",
  githubUsername: "MarcinkPawel",

  currentSkills: [
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "Teamwork",
    "Markdown",
    "Immutability",
    "CSS BEM convention",
    "JavaScript ES6+",
    "CSS Grid",
    "CSS Flexbox",
    "Git",
    "React",
    "React Hooks",
    "React Router",
    "Redux (Toolkit)",
    "Redux-Saga",
    "Error handling",
    "Working with API (fetch, axios)",
    "Promises, Async/Await",
    "GitHub Pull Requests & Review",
    "Trello",
    "Scrum",
    "NPM",
  ],

  skillsToLearn: [
    "TypeScript",
    "Node.js",
    "React Context",
    "Cypress",
    "Unit testing",
    "JS classes",
    "React Native",
  ],
};
